apiVersion: v1
kind: Service
metadata:
  name: task-tracker-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: task-tracker
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000